version: '3'
services:
  pwn:
    restart: always
    container_name: message
    build: .
    working_dir: /home/ctf
    ports:
      - '8008:9999'
    entrypoint: /etc/run_xinetd.sh
    read_only: true

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.104.0/24
