version: '3.9'
services:
  pwn:
    restart: always
    container_name: message
    build: .
    working_dir: /home/ctf
    ports:
      - '8008:9999'
    entrypoint: /etc/run_xinetd.sh
    read_only: true
