version: '3'
services:
  skull:
    build: .
    ports:
      - 10000:10000
    working_dir: /home/ctf
    entrypoint: /etc/init.sh
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.106.0/24
