version: "3"

services:
    babyheap:
        build: .
        restart: always
        ports:
            - "4267:4267"
        read_only: true

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
