version: "3"
services:
  flask:
    build: ./
    volumes:
      - ./:/app
    ports:
      # public:local
      - "54734:5000"
    container_name: spidershamble
    restart: always
    environment:
      - APP_NAME=spidershamble
