version: "3"
services:
  flask:
    build: ./
    volumes:
      - ./:/app
    ports:
      # public:local
      - "28001:5000"
    container_name: jacksworst
    restart: always
    environment:
      - APP_NAME=jacksworst
