version: "3"

services:
    rop:
        build: .
        restart: always
        ports:
            - "42069:42069"
        read_only: true

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
